modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="justenoughbreeding"
version="${file.jarVersion}"
displayName="Just Enough Breeding"
displayURL="https://github.com/Christofmeg/JustEnoughBreeding" #optional
logoFile="icon.png"
authors="Christofmeg"
#credits=""
description="JEI/REI/EMI plugin that displays breeding information"
[[dependencies.justenoughbreeding]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[modproperties.justenoughbreeding]
    catalogueImageIcon="catalogue-icon.png"