modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues" #optional
license="${license}"
[[mods]]
modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="https://github.com/Christofmeg/JustEnoughBreeding" #optional
    logoFile="icon.png"
    authors="${mod_author}"
    description="${description}"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[11.4.0.287,)"
    ordering="NONE"
    side="BOTH"
[modproperties.justenoughbreeding]
    catalogueImageIcon="catalogue-icon.png"