modLoader="javafml"
loaderVersion="[50,)"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues" #optional
license="The MIT License (MIT)"
[[mods]]
    modId="justenoughbreeding"
    version="${version}"
    displayName="Just Enough Breeding"
    displayURL="https://github.com/Christofmeg/JustEnoughBreeding" #optional
    logoFile="icon.png"
    authors="Christofmeg"
    description="JEI/REI/EMI plugin that displays breeding information"
[[dependencies.justenoughbreeding]]
    modId="forge"
    mandatory=true
    versionRange="[50.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"
[modproperties.justenoughbreeding]
    catalogueImageIcon="catalogue-icon.png"