modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues"
license="${license}"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="https://github.com/Christofmeg/JustEnoughBreeding"
    logoFile="icon.png"
    authors="${mod_author}"
    description="${description}"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[15.20,)"
    ordering="NONE"
    side="CLIENT"
[modproperties.${mod_id}]
    catalogueImageIcon="catalogue-icon.png"