#jei_version=19.+
#enable_jei=false
rei_version=20.+
cloth_config_version=19.+
architectury_version=17.+
enable_rei=true
#emi_version=1.1.7
#enable_emi=true

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue
#catalogue_version=5441226

# Jade https://www.curseforge.com/minecraft/mc-mods/jade
jade_version=6713304