jei_version=27.+
enable_jei=true
rei_version=21.+
cloth_config_version=21.+
architectury_version=19.+
enable_rei=false
#emi_version=1.1.7
#enable_emi=true

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue
catalogue_version=7328024

# Jade https://www.curseforge.com/minecraft/mc-mods/jade
jade_version=7886760