# Project
version=1.6.2
group=com.christofmeg.justenoughbreeding
java_version=21

# Mod options
minecraft_version=1.21.5
mod_name=Just Enough Breeding
mod_author=Christofmeg
mod_id=justenoughbreeding
license=The MIT License (MIT)
description=JEI/REI/EMI plugin that displays breeding information
minecraft_version_range=[1.21.5, 1.21.6)

# Fabric | https://fabricmc.net/develop/
fabric_minecraft_version=1.21.5
fabric_supported_versions=1.21.5
fabric_version=0.128.0+1.21.5
fabric_loader_version=0.16.14

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_minecraft_version=1.21.5
neoforge_supported_versions=1.21.5
neoforge_version=21.5.80
neoforge_loader_version_range=[7,)
neoforge_minecraft_version_range=[1.21.5,1.21.6)

# Parchment | https://parchmentmc.org/docs/getting-started
parchment_mc=1.21.5
parchment_version=2025.06.15

# NeoForm for Common | https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# CurseForgeGradle | Minotaur options
cf_id=899386
modrinth_id=9Pk89J3g
release_type=release
fabric_release_versions=1.21.5
neoforge_release_versions=1.21.5

# PackFormat | https://minecraft.wiki/w/Pack_format