# Project
version=3.0.0
group=com.christofmeg.justenoughbreeding
java_version=21

# Mod options
minecraft_version=1.21.11
mod_name=Just Enough Breeding
mod_author=Christofmeg
mod_id=justenoughbreeding
license=The MIT License (MIT)
description=JEI/REI/EMI plugin that displays breeding information
minecraft_version_range=[1.21.11, 1.26.1)

# Fabric | https://fabricmc.net/develop/
fabric_minecraft_version=1.21.11
fabric_supported_versions=1.21.11
fabric_version=0.141.4+1.21.11
fabric_loader_version=0.19.3

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_minecraft_version=1.21.11
neoforge_supported_versions=1.21.11
neoforge_version=21.11.42
neoforge_loader_version_range=[7,)
neoforge_minecraft_version_range=[1.21.11, 1.26.1)

# Parchment | https://parchmentmc.org/docs/getting-started
parchment_mc=1.21.11
parchment_version=2025.12.20

# NeoForm for Common | https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# CurseForgeGradle | Minotaur options
cf_id=899386
modrinth_id=9Pk89J3g
release_type=release
fabric_release_versions=1.21.11
neoforge_release_versions=1.21.11

# PackFormat | https://minecraft.wiki/w/Pack_format