# Project
version=1.6.2
group=com.christofmeg.justenoughbreeding
java_version=21

# Mod options
minecraft_version=1.21.4
mod_name=Just Enough Breeding
mod_author=Christofmeg
mod_id=justenoughbreeding
license=The MIT License (MIT)
description=JEI/REI/EMI plugin that displays breeding information
minecraft_version_range=[1.21.4, 1.21.5)

# Fabric | https://fabricmc.net/develop/
fabric_minecraft_version=1.21.4
fabric_supported_versions=1.21.4
fabric_version=0.112.0+1.21.4
fabric_loader_version=0.16.9

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_minecraft_version=1.21.4
neoforge_supported_versions=1.21.4
neoforge_version=21.4.140
neoforge_loader_version_range=[4,)
neoforge_minecraft_version_range=[1.21.4,1.22)

# Parchment | https://parchmentmc.org/docs/getting-started
parchment_mc=1.21.4
parchment_version=2024.12.07

# NeoForm for Common | https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# CurseForgeGradle | Minotaur options
cf_id=899386
modrinth_id=9Pk89J3g
release_type=release
fabric_release_versions=1.21.4
neoforge_release_versions=1.21.4

# PackFormat | https://minecraft.wiki/w/Pack_format