modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="justenoughbreeding"
version="1.0.2"
displayName="Just Enough Breeding"
displayURL="https://github.com/Christofmeg/JustEnoughBreeding" #optional
logoFile="icon.png"
authors="Christofmeg"
#credits=""
description="JEI plugin that displays breeding information"
[[dependencies.justenoughbreeding]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="jei"
    mandatory=false
    versionRange="[6,)"
    ordering="NONE"
    side="BOTH"
[modproperties.justenoughbreeding]
    catalogueImageIcon="catalogue-icon.png"