modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="justenoughbreeding"
version="${file.jarVersion}"
displayName="Just Enough Breeding"
displayURL="https://github.com/Christofmeg/JustEnoughBreeding" #optional
logoFile="icon.png"
authors="Christofmeg"
#credits=""
description="JEI plugin that displays breeding information"
[[dependencies.justenoughbreeding]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="jei"
    mandatory=false
    versionRange="[7,)"
    ordering="NONE"
    side="BOTH"
[modproperties.justenoughbreeding]
    catalogueImageIcon="catalogue-icon.png"