modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Christofmeg/JustEnoughBreeding/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="justenoughbreeding"
    version="${version}"
    displayName="Just Enough Breeding"
    displayURL="https://github.com/Christofmeg/JustEnoughBreeding"
    logoFile="icon.png"
    logoBlur = false
    authors="Christofmeg"
    description="JEI/REI/EMI plugin that displays breeding information"
[[dependencies.justenoughbreeding]]
    modId="neoforge"
    type="required"
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justenoughbreeding]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"
[modproperties.justenoughbreeding]
    catalogueImageIcon="catalogue-icon.png"