jei_version=23.+
enable_jei=false
rei_version=20.+
cloth_config_version=19.+
architectury_version=17.+
enable_rei=true
#emi_version=5436759
#enable_emi=true
reipc_forge_annotations_version=12.+

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue
catalogue_version=6715864

# Jade https://www.curseforge.com/minecraft/mc-mods/jade
jade_version=6713216