jei_version=25.+
enable_jei=true
#rei_version=20.+
#cloth_config_version=19.+
#architectury_version=17.+
#enable_rei=true
#emi_version=5436759
#enable_emi=true
reipc_forge_annotations_version=12.+

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue
catalogue_version=7061289

# Jade https://www.curseforge.com/minecraft/mc-mods/jade
jade_version=7056468