jei_version=20.+
enable_jei=true
rei_version=18.+
cloth_config_version=17.+
architectury_version=15.+
enable_rei=false
#emi_version=5436759
#enable_emi=true
reipc_forge_annotations_version=12.+

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue
#catalogue_version=5441227

# Jade https://www.curseforge.com/minecraft/mc-mods/jade
jade_version=6170888